### ISSUE TITLE
testWriteN() to many arguments

### ISSUE THREAD

**Issue by Luxovious** [RobTillaart/PCA9634#11]
Hi Rob,

the test function void testWriteN() uses an array of 16 values. As the PCA9634 has only 8 LEDs this might cause some unpredicted behaviour. I assume this is from a PCA9635 test function. This small change has been tested by me and it seems to work fine.

` void testWriteN(){`
` Serial.print(millis());`
` Serial.print("\t");`
` Serial.println("Test - writeN ");`
` uint8_t arr[8] = {16, 32, 64, 96, 128, 160, 192, 255};`
` ledArray.writeN(0, arr, ledArray.channelCount());`
` }`

Best regards Johannes

**Comment by RobTillaart** [comment]
yup, inherited from 9635,

in fact it writes only 8 as ```ledArray.writeN(0, arr, ledArray.channelCount());```  uses the **channelCount()**
but it is a bit confusing,  I agree

**Comment by RobTillaart** [comment]
todo fix file: **PCA9634_test01.ino**

**Comment by RobTillaart** [comment]
updated the example...
