### ISSUE TITLE
Small issue with current example test01

### ISSUE THREAD

**Issue by Luxovious** [RobTillaart/PCA9634#15]
I was experiencing some weird behaviour since I used the library the first time. However, it took me until now to understand the underlying issue. In the function testSetLedDriverModeLEDPWM() the attribute PCA9634_PWM(channel) needs to be replaced by PCA9634_LEDPWM.
Please find the corrected code below.

```cpp
void testSetLedDriverModeLEDPWM()
{
  Serial.print(millis());
  Serial.print("\t");
  Serial.println("Test - PWM-Mode for all channels, with all_call");
  for (int channel = 0; channel < all_call.channelCount(); channel++)
  {
    all_call.setLedDriverMode(channel, PCA9634_LEDPWM);
    if (all_call.getLedDriverMode(channel) != PCA9634_LEDPWM)
    {
      Serial.print(millis());
      Serial.print("\t");
      Serial.print("Channel: ");
      Serial.println(channel);
    }
  }
}
```

**Comment by RobTillaart** [comment]
This looks like a new function to me - it is not in my copy of test01

**Comment by Luxovious** [comment]
Well, in that case I might have created it myself and I forgot about it. 🤷‍♂️

**Comment by Luxovious** [comment]
Stupid me...
