### ISSUE TITLE
Implementation of synchronous output change of multiple PCA9634

### ISSUE THREAD

**Issue by Luxovious** [RobTillaart/PCA9634#18]
Hi Rob,

I have a small feature request which should not require too much work, as it is mostly copy & paste and adapting of pieces already existing within your code.

Currently, after every communication to an individual chip (write1, write3 or writeN) a STOP command is send. This works perfectly fine and I am very happy with it. Just as intended, each chip is adressed individually, all LED outputs are configured individually and then activated on the ACK/STOP command.

```cpp
uint8_t PCA9634::writeN(uint8_t channel, uint8_t* arr, uint8_t count)
{
  if (channel + count > _channelCount)
  {
    _error = PCA9634_ERR_WRITE;
    return PCA9634_ERROR;
  }
  uint8_t base = PCA9634_PWM(channel);
  _wire->beginTransmission(_address);
  _wire->write(base);
  for(uint8_t i = 0; i < count; i++)
  {
    _wire->write(arr[i]);
  }
  _error = _wire->endTransmission();
  if (_error != 0)
  {
    _error = PCA9634_ERR_I2C;
    return PCA9634_ERROR;
  }
  return PCA9634_OK;
}
```
However, your library is already prepared for another feature of the chips. For the PCA963x series, chips are able to synchronise their output change. As a result, the outputs of multiple chips can be configured individually and then activated at the same time. This ensures efficient communication with multiple chips when stricter timing is required. It also reduces the load on the I²C-bus.
This behaviour can be configured with the already existing ACK/STOP configuration in your PCA9634.begin() function. In the configuration options of your library, nothing needs to be changed as it already works flawlessly.

For the feature to work, the communcation needs a little change. This could be achieved by adding a function similar to the writeN-function. The main difference should be a _**missing**_ STOP-command (endTransmission()). Additionally, the endTransmission()-function should be available on its own. Users could then determine when a STOP command should be send and when not.

A communication protocoll using this feature could then be implemented by the individual user of your library. It could look something like this: 

1. Send a START condition for chip1 (``_wire->beginTransmission(_address);``) as in the current writeN-function
2. Send the output configuration as in the current writeN-function
```cpp
  _wire->write(base);
  for(uint8_t i = 0; i < count; i++)
  {
    _wire->write(arr[i]);
  }
``` 
3. Send START condition of chip2 (address of chip2)
4. Send output configuration of chip2
5. Send START condition of chip3 (address of chip3)
6. Send output configuration of chip3
7. Rinse and repeat as many times as you like
8. Send STOP command. This leads to a synchonous activation of all previously configured outputs

This would help to change the output states of a larger number of chips, when the ALLCALL cannot be used (not all PCA963x should be configured with the same outputs). I believe the small addition is a mere copy & paste (with slight adaptations) of your existing code. I am happy to test this feature, in case you are interessted to give it a shot.

Have a nice weekend,
Johannes

**Comment by RobTillaart** [comment]
Good morning Johannes,

I read the issue but my head is not clear enough to get it all so I will read/investigate later. The easy part is to make a test branch for this to get started so I will do that today. There are some tasks pending in my agenda that have prio so responsiveness from my side can be low. 

R.

**Comment by RobTillaart** [comment]
Created a test_86 branch - no code changes yet but at least a place "to play"

**Comment by RobTillaart** [comment]
As code is merged I close the issue
