### ISSUE TITLE
Funktion test on PCA9634 HW: successful

### ISSUE THREAD

**Issue by Luxovious** [RobTillaart/PCA9634#3]
Hi Rob Tillaart,
you did an amazing job with the port towards the PCA 9634. I really apprechiate that you took the time and effort to develop this piece of code! I have checked your version 0.1.0 and it looks **very** promissing. I was not able to find any issues besides the following. I will adapt your examples and use it in many future projects. If you want to, I can send you a completely soldered breakout board of the PCA9634 as a little "thank you", when the PCBs arrive.

My adaptations:
- I use Visual Studio Code/PlatformIO. Therefore, functions need to be declared before use. I changed the sequence a little. I put anything after the setup/loop in front of it.
- Furthermore, I have to add #include <Arduino.h>.
- In your "library.json" and "library.properties" you mention the PCA9635 instead of the PCA9634.

This is the result of my Serial Monitor:
0       Test - Switch all on
10      Test - set pwm mode 
1627    Test - write1 - I
2323    Test - write 1 - II
3018    Test - write3 - random RGB
3023    Test - writeN
3024    Test - GroupPWM
3235    Test - groupFRQ
3447    Test - readMode
3448    PCA9634_MODE1: 1
3449    PCA9634_MODE2: 20
3449    Test - Switch all off
3461    done...

BTW: I did not kill my PCA9634. I was just messing with the addressing -.-
My platform: Arduino pro mini, Win 10, Visual Studio Code with PlatformIO

**Comment by RobTillaart** [comment]
> I use Visual Studio Code/PlatformIO. Therefore, functions need to be declared before use. I changed the sequence a little. I put anything after the setup/loop in front of it.

This is in the examples I guess.


> Furthermore, I have to add #include <Arduino.h>.

Is that in the examples too?


> In your "library.json" and "library.properties" you mention the PCA9635 instead of the PCA9634.

Fixed for 0.1.1  in branch https://github.com/RobTillaart/PCA9634/tree/fix3


TODO:  publish in platformIO too.

**Comment by RobTillaart** [comment]
> If you want to, I can send you a completely soldered breakout board of the PCA9634 as a little "thank you", when the PCBs arrive.

would be appreciated, please send me an email so I can send you the post address - I prefer not to share on GitHub.

**Comment by RobTillaart** [comment]
@Luxovious 

Can you answer the question above about your remarks, so I can fix those?

**Comment by Luxovious** [comment]
I'm sorry, I did not realize you were asking a question, since all your assumptions are correct. I only adapted the examples so they would also run in different IDEs and not only in the Arduino IDE :-).
No changes in the library or the header file required.

**Comment by RobTillaart** [comment]
Merged  and released 0.1.1 

Did not change the order of the functions as for many new programmers setup and loop are reference points.
People working with VS probably know about needing function prototypes (assumption).
