### ISSUE TITLE
Extensive Testing offer of ALL CALL and SUB CALL

### ISSUE THREAD

**Issue by Luxovious** [RobTillaart/PCA9634#33]
Hi Rob,
Currently I am still working on my project which was pushed forward immensely by your port of the PCA9635 library to the PCA9634 chip. I will hopefully reach a point sometime soon (this spring?) in which I will use multiple PCA9634 chips. I will mostly adress them through the ALL CALL command. I am already using ALL CALL for programming and testing on a single chip, however I have not used it on multiple chips. 

My offer: **I am happy to test the ALL CALL and SUB CALL adresses with multiple chips**, as I will need those in my project anyway. If you want me to test them in a specific way or document them in a specific way I am happy to do so. Please let me know if you have any requirements regarding the testing.

I was looking for a paypal.me link in you repo as I intend to donate to your work. I recomment to put your paypal.me-Link into the [FUNDING.yml](https://github.com/RobTillaart/PCA9634/blob/master/.github/FUNDING.yml)-File. since this would safe two currency conversions. The code should probably be something like `custom: ["https://paypal.me/..."]`, as I have seen on other repos.

**Comment by RobTillaart** [comment]
Guten Tag Johannes,

Sounds like you have made progress and the "finish" comes in sight (my assumption).

#### Wrt the tests, 
No I do not have any specific test in mind. However it would be great if you would document and share (part of) your setup and code. Think it would be good to have a separate file e.g. multi_PCA9634.md as a guideline for other users. The level should be understandable by someone who played with a single PCA so they have an easy start.
For all the details the datasheet is the document.

#### Sponsor

I have been working on PayPal, and one option would be to add a badge in the readme file. 
The look of a badge is very nice and one can tune its color and text very easily, see below
Personally I find this a bit intrusive as the libraries would also be cloned and there is my donate button under other peoples account (maybe I'm just old fashioned). More important they would not stand out between the other badges that are about the code. Finally cloned badges could be easily redirect to other PayPal accounts.

Code and badges look (these actually work).
```
[![Sponsor](https://img.shields.io/badge/Sponsor-PCA9634-gold.svg)](https://github.com/sponsors/RobTillaart?o=esb)
[![Sponsor](https://img.shields.io/badge/Sponsor-PayPal_EUR-blue.svg)](https://paypal.me/robtillaart/EUR)
[![Sponsor](https://img.shields.io/badge/Sponsor-PayPal_USD-green.svg)](https://paypal.me/robtillaart/USD)
[![Sponsor](https://img.shields.io/badge/Sponsor-GitHub-red.svg)](https://github.com/sponsors/RobTillaart?o=esb)
```
[![Sponsor](https://img.shields.io/badge/Sponsor-PCA9634-gold.svg)](https://github.com/sponsors/RobTillaart?o=esb)
[![Sponsor](https://img.shields.io/badge/Sponsor-PayPal_EUR-blue.svg)](https://paypal.me/robtillaart/EUR)
[![Sponsor](https://img.shields.io/badge/Sponsor-PayPal_USD-green.svg)](https://paypal.me/robtillaart/USD)
[![Sponsor](https://img.shields.io/badge/Sponsor-GitHub-red.svg)](https://github.com/sponsors/RobTillaart?o=esb)

(I like the blue one most)

Another option would indeed be the FUNDING.yml file as you propose.

I only have it here - https://github.com/RobTillaart/Arduino - on the right side.

The yml file can support multiple funding methods e.g. like 

```yml
# These are supported funding model platforms
github: RobTillaart
custom: ["https://www.paypal.me/robtillaart/EUR", "https://www.paypal.me/robtillaart/USD"]
```

I have a small script that patches all libraries in one go which is almost robust.

There are also other payment methods I could consider like - https://www.buymeacoffee.com/ 
However too many methods looks greedy imho and results in administrative overhead.

**Comment by RobTillaart** [comment]
@Luxovious 
Thanks for the sponsoring, really appreciated!
